@echo off
set CORVETTE_URL=https://github.com/spearmin10/corvette/blob/main/corvette.ps1?raw=true
for /f "usebackq delims=" %%i in (`cmd /c "echo %CORVETTE_URL% | powershell -e JABpAG4AcAB1AHQAIAB8ACAAJQB7AFsAQwBvAG4AdgBlAHIAdABdADoAOgBUAG8AQgBhAHMAZQA2ADQAUwB0AHIAaQBuAGcAKABbAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBuAGkAYwBvAGQAZQAuAEcAZQB0AEIAeQB0AGUAcwAoACIAJgAgACgAWwBTAGMAcgBpAHAAdABCAGwAbwBjAGsAXQA6ADoAQwByAGUAYQB0AGUAKABbAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAXQA6ADoATgBlAHcAKAApAC4ARABvAHcAbgBsAG8AYQBkAFMAdAByAGkAbgBnACgAJwAkAF8AJwApACkAKQAiACkAKQB9AA=="`) do set LAUNCH_CORVETTE_B64=%%i
powershell -e "%LAUNCH_CORVETTE_B64%"
pause
